---
title: "Archetype ggplot Graphs"
author: "Nick Gotelli"
date: "December 22, 2018"
output: 
  html_document: 
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file condenses and simplifies a terrific set of graphs originally posted at:
http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html#top 

To make the examples self-contained, all library calls occur within each example

# Correlation

## Simple scatterplot

```{r}
# Scatterplot

options(scipen=999)  # turn-off scientific notation like 1e+48
library(ggplot2)

scatter1 <- ggplot(mpg, aes(x=cty, y=hwy)) +
  geom_point(aes(col=cyl,size=displ)) +
  geom_smooth(method="loess",se=FALSE,col="red") +  
  xlim(c(0, 40)) + 
  ylim(c(0, 50)) + 
  labs(subtitle="Highway vs City Mileage", 
       y="City Mileage (mpg)", 
       x="Highway Mileage (mpg)", 
       title="Scatterplot", 
       caption = "Source: R-data") +
  theme_bw(base_size=20,base_family="serif") 
```  
### Scatterplot (toy example)

```{r}
plot(scatter1)

# toy example
xVar <- rnorm(100)
yVar <- xVar + 0.2*rnorm(100)
tData1 <-data.frame(xVar=xVar,yVar=yVar)

library(ggplot2)

tscatter1 <- ggplot(tData1,aes(x=xVar,y=yVar)) +
                      geom_point() +
                      geom_smooth(method="lm",se=FALSE)
plot(tscatter1)
                    
```

## Scatterplot with encircling

```{r}

# Scatterplot with encircling
options(scipen=999)  # turn-off scientific notation like 1e+48

library(ggplot2)
library(ggalt)

mpgGrp <- mpg[mpg$class=="compact",] # create a subset data frame for encircling

scatter2 <- ggplot(mpg, aes(x=cty, y=hwy)) +
  geom_point(aes(col=cyl,size=displ)) +
  geom_smooth(method="loess",se=FALSE,col="red") +  
  xlim(c(0, 40)) + 
  ylim(c(0, 50)) + 
  labs(subtitle="Highway vs City Mileage", 
       y="City Mileage (mpg)", 
       x="Highway Mileage (mpg)", 
       title="Scatterplot with encircling", 
       caption = "Source: R-data") +
  theme_bw(base_size=20,base_family="serif") +
  
  geom_encircle(data=mpgGrp,
                aes(x=cty,y=hwy),
                     color="seagreen",
                     size=3,
                     expand=0.08)

plot(scatter2)


```

### Scatterplot with encircling (toy example)

```{r}

# toy example
xVar <- rnorm(100)
yVar <- xVar + 0.2*rnorm(100)
tData2 <-data.frame(xVar=xVar,yVar=yVar)
tsubData2 <- tData2[tData2$xVar > 1 & tData2$yVar > 1,]

library(ggplot2)
library(ggalt)

tscatter2 <- ggplot(tData2,aes(x=xVar,y=yVar)) +
                      geom_point() +
                      geom_smooth(method="lm",se=FALSE) +
             geom_encircle(data=tsubData2,
                           aes(x=xVar,y=yVar),
                           color="red",
                           size=2,
                           expand=0.03)
plot(tscatter2)
                    
```

## Jitter plot
```{r}
# Jitter plot

options(scipen=999)  # turn-off scientific notation like 1e+48
library(ggplot2)

scatter3 <- ggplot(mpg, aes(x=cty, y=hwy)) +
  geom_jitter(width=1, height=1, size=1) +
              # aes(col=cyl,size=displ)) +
  geom_smooth(method="loess",se=FALSE,col="red") +  
  xlim(c(0, 40)) + 
  ylim(c(0, 50)) + 
  labs(subtitle="Highway vs City Mileage", 
       y="City Mileage (mpg)", 
       x="Highway Mileage (mpg)", 
       title="Scatterplot with jittering", 
       caption = "Source: R-data") +
  theme_bw(base_size=20,base_family="serif") 
  

plot(scatter3)

```

## Jitter plot (toy example)
```{r}
# Jitter plot

library(ggplot2)

xVar <- rnorm(100)
yVar <- xVar + 0.5*rnorm(100)
xVar <- round(xVar)
yVar <- round (yVar)
tData3 <- data.frame(xVar=xVar,yVar=yVar)


tscatter3a <- ggplot(tData3, aes(x=xVar, y=yVar)) +
  geom_point() +
  geom_smooth(method="loess",se=FALSE,col="red")   
plot(tscatter3a)

tscatter3b <- ggplot(tData3, aes(x=xVar, y=yVar)) +
  geom_jitter(width=0.1, height=1, size=1) +
  geom_smooth(method="loess",se=FALSE,col="red")   
plot(tscatter3b)

```
## Counts chart

```{r}
options(scipen=999)  # turn-off scientific notation like 1e+48
library(ggplot2)

scatter4 <- ggplot(mpg, aes(x=cty, y=hwy)) +
  geom_count(col="goldenrod",show.legend=TRUE) +
              # aes(col=cyl,size=displ)) +
  geom_smooth(method="loess",se=FALSE,col="red") +  
  xlim(c(0, 40)) + 
  ylim(c(0, 50)) + 
  labs(subtitle="Highway vs City Mileage", 
       y="City Mileage (mpg)", 
       x="Highway Mileage (mpg)", 
       title="Scatterplot with count overlay", 
       caption = "Source: R-data") +
  theme_bw(base_size=20,base_family="serif") 
  

plot(scatter4)


```


## Bubble plot

```{r}
options(scipen=999)  # turn-off scientific notation like 1e+48
library(ggplot2)

mpg_select <- mpg[mpg$manufacturer %in% c("audi", "ford", "honda", "hyundai"), ]

scatter5 <- ggplot(mpg_select, aes(x=displ, y=cty)) +
  geom_jitter(aes(col=manufacturer,size=hwy)) +
  geom_smooth(aes(col=manufacturer),method="lm",se=FALSE) +  
  labs(subtitle="Highway Mileage vs Displacement", 
       y="City Mileage (mpg)", 
       x="Highway Mileage (mpg)", 
       title="Bubble plot with highway as point size", 
       caption = "Source: R-data") +
  theme_bw(base_size=20,base_family="serif") 
  

plot(scatter5)


```
